# Input variables
# - Core R release number (e.g. 3.6.2)
# - Postgresql release number (e.g. 11.5)
# - RDS target URL
# - RDS target credentials
# - Environment name?

variables:
  POSTGRES_DB: iatlas_dev
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: docker
  R_VERSION: "3.6.2"

stages:
  - test_data
  - build_data
  - deploy_to_staging
  - deploy_to_prod

# Test Data:
#   stage: test_data
#   image: rocker/verse:${R_VERSION}
#   only:
#     - staging
#   script:
#     - R -e "d"

Build Database:
  stage: build_data
  only:
    - feature/feather_file_structure
  image: rocker/verse:${R_VERSION}
  services:
    - postgres:11.5
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - /tmp/*.pgdata
  artifacts:
    name: "iatlas_data_${CI_COMMIT_REF_NAME}"
    paths:
      - /tmp/*.pgdata
  variables:
    DB_HOST: postgres
  script:
    # Update the Apt cache
    - sudo apt-get -y update
    # Install the Postgres 11 client
    - sudo apt-get -y install postgresql-client-11
    # Build the database structure
    - cd ${CI_PROJECT_DIR}/sql; psql -a "postgres://postgres:docker@postgres/postgres" create_dev_db.sql
    # Build the data
    - cd ${CI_PROJECT_DIR}; R -e "source('build_data_in_CI.R')"
    # Do a binary dump of the database
    - pg_dump "postgres://postgres:docker@postgres/iatlas_staging" --format custom -f ${CI_PROJECT_DIR}/iatlas_dev.pgdata

Deploy To Staging:
  stage: deploy_to_staging
  only:
    - feature/feather_file_structure
  image: postgres:11.5
  variables:
    # Don't pull the repo into this stage, it's not needed
    GIT_STRATEGY: none
    STAGING_DB_NAME: iatlas_staging
    STAGING_DB_HOST: sage-test.cau5la50px0r.us-west-2.rds.amazonaws.com
    STAGING_DB_USER: postgres
  script:
    - scripts/gitlab_build_db.sh $STAGING_DB_HOST $STAGING_DB_USER $STAGING_DB_PASSWORD $STAGING_DB_NAME
